### ISSUE TITLE
Cannot start with SQLITE configuration[BUG]

### ISSUE THREAD

**Issue by JiriMON** [waccit/unified-red#72]
**Describe the bug**
After installing unified-red and setting sqlite connection node-red fails to start with errors:

3 Jan 16:35:34 - [red] Uncaught Exception:
3 Jan 16:35:34 - [error] Error
    at Database.<anonymous> (/home/mon/.node-red/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /home/mon/.node-red/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/home/mon/.node-red/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /home/mon/.node-red/node_modules/sequelize/lib/sequelize.js:314:28
    at async SQLiteQueryInterface.select (/home/mon/.node-red/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Role.findAll (/home/mon/.node-red/node_modules/sequelize/lib/model.js:1134:21)
    at async Role.findOne (/home/mon/.node-red/node_modules/sequelize/lib/model.js:1228:12)
    at async init (/home/mon/.node-red/node_modules/unified-red/api/users/role.service.js:10:11)

**To Reproduce**
1. Go to install unified-red
2. On initial setup page set sqlite:/tmp/unified-red.db
3. Click test
4. click install
5. restart node-red

**Affected Environment (please select one or more):**
[ x] Node-RED
[ x] Unified-RED
[ ] Backend

**Context:**
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
* Operating System:  Linux 5.15.79.1-microsoft-standard-WSL2 x64 LE
* Node.js version: v19.3.0
* npm version: 9.2.0
* Node-RED version: v3.0.2
* Unified-RED version:  2.3.0

**Comment by wac-dirka** [comment]
This issue has been resolved with the release of v2.6.0.
